### ISSUE TITLE
postgresql_from_r script not compiling

### ISSUE THREAD

**Issue by leonthoma** [data-hydenv/lectures#1]
When attempting to knit the file I get the error

Line 83  Error in postgresqlgetResult(new.con) : RS-DBI driver: (could not Retrieve the result : ERROR: Geometry SRID (0) does not match column SRID (4326) CONTEXT: COPY hobo, line 1, column geom: "POINT(7.8 48.0)" )

**Comment by mmaelicke** [comment]
As I showed in lecture, there is something missing. The value of the ``geom`` attribute, which is of type ``Geometry`` has to be set including information about the spatial reference system.
Change the respective code to 

```sql
'SRID=4326;POINT (7.8 48.0)'
```

and this part should work

**Comment by mmaelicke** [comment]
fixed with [d0ea503](https://github.com/data-hydenv/lectures/commit/d0ea503e9f8c3b33e3d87ebfdebc9fcc916b8e35), therefore closing this issue.
