### ISSUE TITLE
introduction_sql non meaningful output

### ISSUE THREAD

**Issue by leonthoma** [data-hydenv/lectures#2]
The chunk at L190 produces a table with 0 rows

**Comment by mmaelicke** [comment]
Thanks for reporting. 
But I cannot confirm. Just re-opened the file, cleared the output. Then created a connection and run that chunk only. I am seeing this:

![image](https://user-images.githubusercontent.com/2826034/72611476-89b56e80-392a-11ea-8371-9d2f4a391407.png)

Can you try again from a clean copy running only that chunk (after running the first one to get a con object) ?

**Comment by leonthoma** [comment]
This is not the code that is on github (might have been updated already but I cloned the repo today)
Original code is
`
select h.hobo_id, radiation_influence, count(tstamp) as amount, avg(temperature) as mean_t, avg(light) as mean_light 
from raw_data r
join hobo h on h.hobo_id=r.hobo_id
group by h.hobo_id, radiation_influence
`
Error was in L193: `join hobo h on h.hobo_id=r.hobo_id` instead of `join hobo h on h.id=r.hobo_id`

**Comment by mmaelicke** [comment]
You are right, again. These were the changes that I showed in class, but not upload so far.
They have been fixed on Github with [9d2568](https://github.com/data-hydenv/lectures/commit/3c7fe044c3e3cf40ad926fd9fa97b3e5529d2568), as well.
Thanks!
